### PR TITLE
CI Check GitHub Actions + CircleCI running on PR

### PR DESCRIPTION
**Pull request by thomasjpfan**
Testing GitHub Actions with CircleCI

### CODE REVIEW

**Comment by thomasjpfan** [comment]
@alfaro96 Looks like you need to approve before the CI can run.

**Comment by alfaro96** [comment]
I forgot to activate `Build forked pull requests`, so I think that's why your `circleci` jobs are not executed. Could you trigger it again to check if it is now working?

**Comment by alfaro96** [comment]
Thanks @thomasjpfan for helping with the testing process. The last run failed to trigger the job for hosting the documentation because I forgot to include `/head/` at the end of the branch name (the error was `Branch not found`). Now, it should work.

I am sorry for the inconvenience, but could you merge to apply this change and so check if it is working now?

Thank you very much!

**Comment by alfaro96** [comment]
Closing because I can debug by myself, as `circleci` now recognizes my pull request.

Thank you for all the help!

**Pull request closed without merging**
